### ISSUE TITLE
Test k-fold cross validation

### ISSUE THREAD

**Issue by huang1ei** [lmudeeplearninglab/Autopipe#1]

**Comment by ablee99** [comment]
We need to test this!!

**Comment by EARound** [comment]
Have you guys been able to run the code on your workstations?  I am still battling environment issues, currently HDF5 library, and building the GUI, installed GNUWIN make function, still does not build the code.  I will continue my efforts this evening but if you have any suggestions I'm all ears.

**Comment by EARound** [comment]
had to install tensorflow, keras, scikit, matplotlib, and modified hdf5.dll and hdf5_h1.dll in h5py library in autopipe environment to run on local environment.  additionally modified import lines beginning with "from autopipe" to remove that phrase in model.py, serialize.py, modified serialize.ph image_dir.  Succeeded in cycling code from command line.

**Comment by EARound** [comment]
k-fold cross validation successfully implemented.
